[package]
name = "cursed-collections"
description = "Collections that (seem) to break Rust safety."
version = "0.6.2"
authors = ["Simon Génier <simon.genier@protonmail.com>"]
homepage = "https://github.com/kolmogorov-fan-account/cursed-collections"
license = "GPL-3.0+"
readme = "README.md"
edition = "2018"

[dependencies]
hashbrown = "0.12"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
